---
# nginx-1.17.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1.17-replicas
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: library/nginx:1.17
        ports:
        - containerPort: 80
