---
# my-pv-claim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pv-claim
spec:
  storageClassName: fast.ru-1a
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
